### ISSUE TITLE
Why is the bot offline?

### ISSUE THREAD

**Issue by masonthe1** [GanerCodes/videoEditBot#29]
On Discord, the bot is offline for no reason.
![Screenshot 2022-02-05 2 02 18 PM](https://user-images.githubusercontent.com/71143249/152655230-90f83f35-d22f-455e-a256-040a4d953580.png)
Why?

**Comment by masonthe1** [comment]
can you just stop going online and offline for 3 hours for no reason. please go auto.

**Comment by GanerCodes** [comment]
The server it's being ran on isn't in my control, literally he disconnects it from the internet whenever he plays games because it causes lag and will often forget to plug it back in. Once I have an actual hosting solution the uptime will be more consistent and I'll push a big-ish update to VEB I have saved
